### PR TITLE
Migrated the site and docs to gatsby and implemented the new design.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Hi! :slightly_smiling_face: 
The PR contains Code of the migrated version of theia-website to Gatsby with the new design as suggested in #31  This is what it looks like now 
## Home Page
image

## Docs

image

### CODE REVIEW

**Comment by svenefftinge** [comment]
I noticed that when I first get on the website in a very narrow view, the menu is expanded. I think it should be collapsed by default. IF I collapse it then and make the browser window wider again, the website doesn't have a menu at all.

**Comment by nisarhassan12** [comment]
> I noticed that when I first get on the website in a very narrow view, the menu is expanded. I think it should be collapsed by default. IF I collapse it then and make the browser window wider again, the website doesn't have a menu at all.

Thanks! @svenefftinge Great Catch. I think I have to change significantly the way I have coded the Nav.

**Comment by svenefftinge** [comment]
Thank you for updating the DCO. I'll take over the PR from here and make some adjustments on top.
Please do the fix for the menu on a separate PR.

**Comment by nisarhassan12** [comment]
Ok. Thanks :)

**Comment by svenefftinge** [comment]
reopened in #34

**Pull request closed without merging**
