### PR TITLE
Update links after org move

### PR DESCRIPTION
**Pull request by vince-fugnitto**
Update the links from `theia-ide` to `eclipse-theia`.

Based on [comment](https://github.com/eclipse-theia/theia/issues/6182) from the main repo.

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by jankeromnes** [comment]
Oh no, it seems like I just duplicated your work in #58. 😓

But luckily, we came up with the exact same fixes independently (I diffed our diffs), which is an encouraging sign.

**Comment by vince-fugnitto** [comment]
> Oh no, it seems like I just duplicated your work in #58. 😓
> 
> But luckily, we came up with the exact same fixes independently (I diffed our diffs), which is an encouraging sign.

That's alright :) I'll let you merge yours no problem 👍

**Comment by jankeromnes** [comment]
> That's alright :) I'll let you merge yours no problem 👍

Thanks @vince-fugnitto! (I'll add you as a co-author then. 😋)

> It looks more complete than mine (ex: 'https' changes)

I indeed added a second drive-by commit, to fix a few non-canonical URLs (for minor SEO benefits).

**Comment by vince-fugnitto** [comment]
> > That's alright :) I'll let you merge yours no problem 👍
> 
> Thanks @vince-fugnitto! (I'll add you as a co-author then. 😋)

Thank you, that's kind of you 😄 

> > It looks more complete than mine (ex: 'https' changes)
> 
> I indeed added a second drive-by commit, to fix a few non-canonical URLs (for minor SEO benefits).

Sounds good!

**Comment by vince-fugnitto** [comment]
Closing in favor of #58 👍

**Pull request closed without merging**
