### PR TITLE
Optimize the website

### PR DESCRIPTION
**Pull request by jankeromnes**
✔️ Fixed several typos.

✔️ Made the website **2.6 MB lighter**, fixing:

Screenshot 2019-08-27 at 16 19 40

### CODE REVIEW

**Comment by jankeromnes** [comment]
@nisarhassan12 Please take a look when you have time. 🙂

**Comment by jankeromnes** [comment]
Hi Daniel! Cool, thanks a lot for spotting that other typo. I'm sure there are more of these scattered around the website, but I'll fix this one here. 🙂

I'll also contribute this typo to https://github.com/codespell-project/codespell, because it's probably somewhat common.

> By the way, the new website is beautiful 😃 Very clean.

Haha thanks, I agree! This is all @nisarhassan12's work. 💯

**Comment by nisarhassan12** [comment]
@jankeromnes! Thanks! A lot for the PR. The site is more :rocket: fast now :pray: 

I'm also inspired by your commit messages they are very descriptive, clear and  concise. I'm learning a lot from them :slightly_smiling_face: 

By the way, what tool you use for image compression  I use [squoosh.app](https://squoosh.app) which is great but it requires some manual work for each image. Also, I will in a few days I will set up [`gatsby-remark-images`](https://www.gatsbyjs.org/packages/gatsby-remark-images/) to this process.

Finally, I took a few minutes to learn about rel="noopener" and rel="noreferrer".

**Comment by nisarhassan12** [comment]
Thanks! a lot @danieltomasku for spotting the typo :pray: :smile:

**Comment by jankeromnes** [comment]
> I'm also inspired by your commit messages they are very descriptive, clear and concise. I'm learning a lot from them 🙂

Woohoo! I'm really happy that they're useful to you. 😄 

> By the way, what tool you use for image compression

For SVG, you already know https://jakearchibald.github.io/svgomg/.

For the PNGs, I simply thought that it didn't make sense to have photo-sized pictures as a background, and since they were PNGs, I searched online for "optimize PNG", and found https://tinypng.com/ (first result) which worked really well: it saved 90% of each image, without any visible difference.

> Code Spell is amazing 🌟 Thanks for mentiong it.

Yes, I really like codespell. Unfortunately, it's dictionary-based, so it will miss all typos that it doesn't already know. And also, it generates a lot of false-positives (especially inside a `node_modules/` directory, so it's better to remove it before using codespell), so you'll have to double-check every fix it makes.

**Pull request merged**
