### PR TITLE
Update to Theia's new repository URL

### PR DESCRIPTION
**Pull request by jankeromnes**
https://github.com/theia-ide/theia → https://github.com/eclipse-theia/theia

### CODE REVIEW

**Comment by jankeromnes** [comment]
Accidentally duplicates #57, but also includes a few (minor) SEO improvements.

**Comment by vince-fugnitto** [comment]
@jankeromnes is something holding back the merge?

**Comment by jankeromnes** [comment]
@nisarhassan12 Could you please merge this? 🙂

**Comment by nisarhassan12** [comment]
@jankeromnes Yes! Sure! You have added trailing slashes to nav links. I'm curious to know what benefit do they provide :slightly_smiling_face: ?
image

**Comment by jankeromnes** [comment]
Thanks a lot @nisarhassan12!

> You have added trailing slashes to nav links. I'm curious to know what benefit do they provide 🙂 ?

I believe that websites need to decide which link is "canonical" (with or without slash, how it's capitalized, what the exact domain and protocol are, etc) and then need to use the canonical link precisely wherever possible (internal links like here, links on other websites, etc) in order to maximize their SEO.

For example, if a website `example.com` has a page with canonical link `example.com/hello`, but many other websites all decide to link to `example.com/hello/` instead, I believe that Google considers this a different page, and thus the many inbound links won't increase the score of the canonical page with non-slash URL.

I noticed that the canonical URLs for these pages have trailing slashes, so I decided to make the internal links respect that. This may improve the search rank (not sure about this), and also makes sure that users always visit (and potentially share) canonical URLs.

**Comment by nisarhassan12** [comment]
> Thanks a lot @nisarhassan12!
> 
> > You have added trailing slashes to nav links. I'm curious to know what benefit do they provide slightly_smiling_face ?
> 
> I believe that websites need to decide which link is "canonical" (with or without slash, how it's capitalized, what the exact domain and protocol are, etc) and then need to use the canonical link precisely wherever possible (internal links like here, links on other websites, etc) in order to maximize their SEO.
> 
> For example, if a website `example.com` has a page with canonical link `example.com/hello`, but many other websites all decide to link to `example.com/hello/` instead, I believe that Google considers this a different page, and thus the many inbound links won't increase the score of the canonical page with non-slash URL.
> 
> I noticed that the canonical URLs for these pages have trailing slashes, so I decided to make the internal links respect that. This may improve the search rank (not sure about this), and also makes sure that users always visit (and potentially share) canonical URLs.

Thanks! @jankeromnes

**Pull request merged**
