### PR TITLE
[docs] Enable syntax coloring for code snippets

### LINKED ISSUE #39: [docs] Syntax coloring
The code snippets should be syntax colored. See https://github.com/gitpod-io/website on how to do that.

### PR DESCRIPTION
**Pull request by jankeromnes**
Fixes #39.

Inspired from afc30f194b72e122bbc18bda2cf435571b7cf17b.

### CODE REVIEW

**Comment by jankeromnes** [comment]
Thgis correctly sets up the code snippets in the docs, but then the front-end seems to be missing the styles for specific languages like `json` and `ts`:

Screenshot 2019-08-29 at 15 05 36

**Comment by nisarhassan12** [comment]
@jankeromnes Maybe the reason why this is not working has something to do with MDX

**Comment by nisarhassan12** [comment]
The issue that we are having is the same as https://github.com/ChristopherBiscardi/gatsby-mdx/issues/357 the code appears within <pre><code> tags but the content is unparsed and without the wrapper <div class="gatsby-highlight">.

The repository is now archived by the maintainer.

Maybe we can remove MDX and the syntax colouring would work fine.

**Comment by nisarhassan12** [comment]
Closing this in favour of #104 The syntax colouring now works.

**Pull request closed without merging**
