### PR TITLE
Add Huawei to the list of contributors and adopters.

### PR DESCRIPTION
**Pull request by jankeromnes**
Huawei seems to really like Theia, and have requested to be listed in the contributors & adopters list.

I've simply added the logo to the list, but maybe the layout will need some adjustment, because it currently creates a 3rd logo line with just one logo:

Screenshot 2020-04-02 at 15 43 49

@nisarhassan12 Please take a look when you have time.

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@jankeromnes for my own understanding and reference, do you know of contributions or applications that Huawei has contributed to? I could not find contributions in the main-repo with a Huawei email sign-off (which makes me think they perhaps used personal emails if any).

**Comment by akosyakov** [comment]
Huawei build Cloud IDE based on Theia: https://mp.weixin.qq.com/s/K1XEWZFASspMpNppaM2g_A

**Comment by marcdumais-work** [comment]
> Huawei built Cloud IDE based on Theia: https://mp.weixin.qq.com/s/K1XEWZFASspMpNppaM2g_A

Good find. Even with the English translation I had to read until the screenshot at the end to conclude they were using Theia. Maybe a mention would have been nice :)

**Comment by marcdumais-work** [comment]
@svenefftinge I am ok setting the bar low, middle or high, about what constitutes a Theia contributor/adopter, as long as we have a consistent definition, that we apply it fairly to all candidates. 

At the end of the day, more adopters is better, so maybe we go with a low bar? IMHO, with the info I have for this company's Theia-related activities, this is about as low and we should accept, if the inclusion is to have some meaning.

**Comment by jankeromnes** [comment]
Thanks to @nisarhassan12's CSS help, the Contributors & Adopters section now looks like this:

Screenshot 2020-04-03 at 10 04 50

**Comment by jankeromnes** [comment]
Actually, obsessing over it a little bit more, I think centering the last row looks weird now that we have more than 2 rows (I suggested it, but just realized it breaks the grid pattern, which isn't nice).

So, removing the centering again. I think this looks better:

Screenshot 2020-04-03 at 10 12 59

(Note, we could also have centered the middle row, by having 4 then 3 then 4 logos again, but this is splitting hairs at this point. 😅)

**Comment by akosyakov** [comment]
good to merge?

**Comment by nisarhassan12** [comment]
> good to merge? 

@akosyakov yes.

**Pull request merged**
